---
- name: Deploy and Manage Kubernetes Resources
  hosts: kube
  collections:
    - kubernetes.core
  tasks:
    - name: Copy files from flask folder to remote host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /tmp/
      with_fileglob:
        - /home/ubuntu/flask/k8s/flask/*

    - name: Copy files from mysql folder to remote host
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /tmp/
      with_fileglob:
        - /home/ubuntu/flask/k8s/mysql/*

    - name: Copy ingress.yaml to remote host
      ansible.builtin.copy:
        src: /home/ubuntu/flask/k8s/ingress.yaml
        dest: /tmp/

    - name: Delete Kubernetes resources on remote host
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('template', item) | from_yaml }}"
      with_items:
        - "/tmp/flask-config.yaml"
        - "/tmp/flask-deployment.yaml"
        - "/tmp/mysql-config.yaml"
        - "/tmp/mysql-deploy.yaml"
        - "/tmp/mysql-lb.yaml"
        - "/tmp/mysql-ns.yaml"
        - "/tmp/mysql-pv.yaml"
        - "/tmp/mysql-pvc.yaml"
        - "/tmp/ingress.yaml"
        - "/tmp/flask-service.yaml"
        - "/tmp/mysql-service.yaml"

    - name: Apply Kubernetes resources on remote host
      kubernetes.core.k8s:
        definition: "{{ lookup('template', item) | from_yaml }}"
      with_items:
        - "/tmp/flask-config.yaml"
        - "/tmp/flask-deployment.yaml"
        - "/tmp/mysql-config.yaml"
        - "/tmp/mysql-deploy.yaml"
        - "/tmp/mysql-lb.yaml"
        - "/tmp/mysql-ns.yaml"
        - "/tmp/mysql-pv.yaml"
        - "/tmp/mysql-pvc.yaml"
        - "/tmp/ingress.yaml"
        - "/tmp/flask-service.yaml"
        - "/tmp/mysql-service.yaml"