---
- name: Deploy Kubernetes Resources
  hosts: kube
  collections:
    - kubernetes.core
  tasks:
    - name: Copy files from flask folder
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/ubuntu/res/
      with_fileglob:
        - /home/ubuntu/flask/k8s/flask/*

    - name: Copy files from mysql folder
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/ubuntu/res/
      with_fileglob:
        - /home/ubuntu/flask/k8s/mysql/*

    - name: Copy ingress.yaml to remote host
      ansible.builtin.copy:
        src: /home/ubuntu/flask/k8s/ingress.yaml
        dest: /home/ubuntu/res/

    - name: Deleting Kubernetes resources
      kubernetes.core.k8s:
        state: absent
        src: "/home/ubuntu/res/{{ item }}"
      with_items:
        - flask-config.yaml
        - flask-ns.yaml
        - ingress.yaml
        - mysql-deploy.yaml
        - mysql-ns.yaml
        - mysql-pvc.yaml
        - flask-deployment.yaml
        - flask-service.yaml
        - mysql-config.yaml
        - mysql-lb.yaml
        - mysql-pv.yaml
        - mysql-service.yaml
        - mysql-secret.yaml
        - flask-secret.yaml

    - name: Applying Kubernetes resources
      kubernetes.core.k8s:
        state: present
        src: "/home/ubuntu/res/{{ item }}"
      with_items:
        - flask-config.yaml
        - flask-ns.yaml
        - ingress.yaml
        - mysql-deploy.yaml
        - mysql-ns.yaml
        - mysql-pvc.yaml
        - flask-deployment.yaml
        - flask-service.yaml
        - mysql-config.yaml
        - mysql-lb.yaml
        - mysql-pv.yaml
        - mysql-service.yaml
        - mysql-secret.yaml
        - flask-secret.yaml