- name: Deploy Kubernetes Resources
  hosts: kube
  collections:
    - kubernetes.core
  vars:
    src_dir_flask: /home/ubuntu/flask/k8s/flask
    src_dir_mysql: /home/ubuntu/flask/k8s/mysql
    dest_dir: /home/ubuntu/res
    ingress_file: /home/ubuntu/flask/k8s/ingress.yaml
    resources:
      - flask-ns.yaml
      - mysql-ns.yaml
      - flask-secret.yaml
      - flask-config.yaml
      - flask-deployment.yaml
      - mysql-config.yaml
      - mysql-secret.yaml
      - mysql-pv.yaml
      - mysql-pvc.yaml
      - mysql-deploy.yaml
      - mysql-service.yaml
      - flask-service.yaml
      - mysql-lb.yaml
      - ingress.yaml

  tasks:
    - name: Create destination directory if it does not exist
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory
        mode: '0755'

    - name: Copy files from flask folder
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ dest_dir }}/"
      with_fileglob:
        - "{{ src_dir_flask }}/*"

    - name: Copy files from mysql folder
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ dest_dir }}/"
      with_fileglob:
        - "{{ src_dir_mysql }}/*"

    - name: Copy ingress.yaml to remote host
      ansible.builtin.copy:
        src: "{{ ingress_file }}"
        dest: "{{ dest_dir }}/"

#    - name: Deleting Kubernetes resources
#      kubernetes.core.k8s:
#        state: absent
#        src: "{{ dest_dir }}/{{ item }}"
#      with_items: "{{ resources }}"
#      ignore_errors: true  # Ignore errors to ensure idempotency

    - name: Applying Kubernetes resources
      kubernetes.core.k8s:
        state: present
        src: "{{ dest_dir }}/{{ item }}"
      with_items: "{{ resources }}"