---
- name: Deploy Kubernetes Resources
  hosts: kube
  collections:
    - kubernetes.core
  tasks:
    - name: Copy files from flask folder
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /tmp/
      with_fileglob:
        - /home/ubuntu/flask/k8s/flask/*

    - name: Copy files from mysql folder
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /tmp/
      with_fileglob:
        - /home/ubuntu/flask/k8s/mysql/*

    - name: Copy ingress.yaml to remote host
      ansible.builtin.copy:
        src: /home/ubuntu/flask/k8s/ingress.yaml
        dest: /tmp/

    - name: Delete Kubernetes resources
      kubernetes.core.k8s:
        state: absent
        src: /tmp/*.yaml
      register: delete_result

    - name: Apply Kubernetes resources
      kubernetes.core.k8s:
        state: present
        src: /tmp/*.yaml
