---
- name: Deploy Kubernetes Deployment and Service
  hosts: kube
  collections:
    - kubernetes.core
  tasks:
    - name: Copy deployment.yaml to remote host
      ansible.builtin.copy:
        src: /home/ubuntu/flask/k8s/deployment.yaml
        dest: /tmp/deployment.yaml

    - name: Delete existing deployment
      kubernetes.core.k8s:
        state: absent
        src: /tmp/deployment.yaml

    - name: Apply new deployment
      kubernetes.core.k8s:
        state: present
        src: /tmp/deployment.yaml

    - name: Copy service.yaml to remote host
      ansible.builtin.copy:
        src: /home/ubuntu/flask/k8s/service.yaml
        dest: /tmp/service.yaml

    - name: Delete existing service
      kubernetes.core.k8s:
        state: absent
        src: /tmp/service.yaml

    - name: Apply new service
      kubernetes.core.k8s:
        state: present
        src: /tmp/service.yaml

    - name: Copy ingress.yaml to remote host
      ansible.builtin.copy:
        src: /home/ubuntu/flask/k8s/ingress.yaml
        dest: /tmp/ingress.yaml

    - name: Delete existing ingress
      kubernetes.core.k8s:
        state: absent
        src: /tmp/ingress.yaml

    - name: Apply new ingress
      kubernetes.core.k8s:
        state: present
        src: /tmp/ingress.yaml