---
- name: Deploy Kubernetes Resources
  hosts: kube
  collections:
    - kubernetes.core
  tasks:
    - name: Copy files from flask folder
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/ubuntu/res/
      with_fileglob:
        - /home/ubuntu/flask/k8s/flask/*

    - name: Copy files from mysql folder
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/ubuntu/res/
      with_fileglob:
        - /home/ubuntu/flask/k8s/mysql/*

    - name: Copy ingress.yaml to remote host
      ansible.builtin.copy:
        src: /home/ubuntu/flask/k8s/ingress.yaml
        dest: /home/ubuntu/res/

    - name: Apply Kubernetes resources
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', item) }}"
      with_items:
        - /home/ubuntu/res/flask-config.yaml
        - /home/ubuntu/res/flask-ns.yaml
        - /home/ubuntu/res/ingress.yaml
        - /home/ubuntu/res/mysql-config.yaml
        - /home/ubuntu/res/mysql-lb.yaml
        - /home/ubuntu/res/mysql-pv.yaml
        - /home/ubuntu/res/mysql-service.yaml
        - /home/ubuntu/res/flask-deployment.yaml
        - /home/ubuntu/res/flask-service.yaml
        - /home/ubuntu/res/mysql-deploy.yaml
        - /home/ubuntu/res/mysql-ns.yaml
        - /home/ubuntu/res/mysql-pvc.yaml