version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "Installing dependencies and logging into Amazon ECR..."
      - apt-get update -y
      - apt-get install -y awscli
      - aws --version
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region <your-region> | docker login --username AWS --password-stdin <your-ecr-repo-url>
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Fetching the repository URL..."
      - REPOSITORY_URI=<your-ecr-repo-url>
      - echo "Repository URI: $REPOSITORY_URI"
      - echo "Pre-build phase complete."
  build:
    commands:
      - echo "Starting build phase..."
      - echo "Building the Docker image..."
      - docker build -t my-docker-image .
      - echo "Tagging the Docker image..."
      - docker tag my-docker-image:latest $REPOSITORY_URI:latest
      - echo "Build phase complete."
  post_build:
    commands:
      - echo "Starting post-build phase..."
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push $REPOSITORY_URI:latest
      - echo "Post-build phase complete."
artifacts:
  files:
    - '**/*'
  discard-paths: yes
