apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-config
  namespace: mysql-flask
data:
  MYSQL_DATABASE: "dbs"
  MYSQL_USER: "rohit"
  schema.sql: |
    CREATE DATABASE IF NOT EXISTS dbs;
    USE dbs;

    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(50) NOT NULL UNIQUE,
        email VARCHAR(100) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL
    );