apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: rohitpt.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: c-ip
                port:
                  number: 80
          - path: /flask
            pathType: Prefix
            backend:
              service:
                name: c-ip
                port:
                  number: 80
