apiVersion: v1
kind: Service
metadata:
  name: my-LB-service
  namespace: default
spec:
  selector:
    app: flask-app
  type: Loadbalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
