apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: flask
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP  
